### ISSUE TITLE
Debugger visualizer doesn't work in VS2019

### ISSUE THREAD

**Issue by mshtang** [shimat/opencvsharp#1155] opened 2021-01-10 16:16 UTC
# Summary of your issue

The debugger says `unable to load the custom visualizer` with **additional information**: 
```Unable to cast object of type 'OpenCvSharp.DebuggerVisualizers.MatDebuggerVisualizer' to type 'Microsoft.VisualStudio.DebuggerVisualizer.DialogDebuggerVisualizer'```

# Environment
VS2019 Version 16.8.3

# What did you do when you faced the problem?
Dowloaded the OpenCvSharp-4.5.1-20201230.zip release, extracted the DebuggerVisualizers and placed the `OpenCvSharp.DebuggerVisualizers.dll` in the `..Documents\\Visual Studio 2019\\Visualizers` folder.

My project's target framework is .net 4.7.2. The OpenCvSharp package (Version 4.3.0.20200421) is obtained via NuGet. 

## What did you intend to be?

I did see a magnifying glass symbol in the debugger when the cursor war placed over a mat object. But when I clicked it, I got a prompt saying the error in "Summary of your issue" section. I would expect to see an image instead. 

Any help to resolve the issue is highly appreciated! Thanks a lot!

**Comment by yangzhongke** [comment] 2021-01-20 03:18
@shimat  Have you begin solving this issue? If not, maybe I will try to check and solve it, because I used to write visual studio extensions.

**Comment by shimat** [comment] 2021-01-20 03:33
No, I haven't started it yet. Thanks!

**Comment by yangzhongke** [comment] 2021-01-20 20:22
Sorry, but I cannot reproduce the error. It works fine on my computer.
![image](https://user-images.githubusercontent.com/13821363/105230442-4c6c6800-5ba0-11eb-9e98-da9ed57bf212.png)

**Comment by Knudde95** [comment] 2021-06-03 10:08
I had the exact same problem mshtang described. I tried updating OpenCVSharp, Visual Studio, the DebuggerVisualizer but nothing helped. (I was debugging a Dotnet Core 3.1 application if it matters.)

I eventually got it to work by downloading the source code of the DebuggerVisualizer and compiling it myself.
In the DebuggerVisualizer solution, I removed the reference to _"VSSDK.DebuggerVisualizers"_ and added a reference to _"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Packages\Debugger\Visualizers\net2.0\Microsoft.VisualStudio.DebuggerVisualizers.dll"_

Then it started complaining that the debuggee-side visualizer assembly was not found at path _"Documents\Visual Studio 2019\Visualizers\netcoreapp"_ and _"Documents\Visual Studio 2019\Visualizers\netstandard2.0"_. Which I somehow fixed by making new folders called "netcoreapp" and _"netstandard2.0"_ in the _"Visual Studio 2019\Visualizers"_ folder and copying the _"OpenCvSharp.DebuggerVisualizers.dll"_ in both of these folders.

Now it works (until maybe someday a VS update breaks it again).

I Hope this helps.

**Closed** 2021-12-10 12:14 UTC
Labels: wontfix
