### ISSUE TITLE
How to enable GPU processing

### ISSUE THREAD

**Issue by faraoman** [shimat/opencvsharp#312] opened 2017-02-21 08:15 UTC
Hi, I'm writing this for ask you how to enable the GPU processing with your library.
Reading inside the past issues, I've read about compiling an opencv library, but how can I do this?
Can you help me for do that?

Thanks

**Comment by dsoronda** [comment] 2019-02-01 14:38
This should be closed as duplicate of #238.

**Closed** 2020-07-31 16:55 UTC
Labels: wontfix
