### ISSUE TITLE
GaussianBlur with UseOptimized 64 bit adds a band to the top

### ISSUE THREAD

**Issue by garykhollingshead** [shimat/opencvsharp#542] opened 2018-10-17 00:17 UTC
# Summary of your issue
When doing a GaussianBlur on a 32F1C Mat (32.0 sigma), I get a banding effect at the top of my resulting image when Cv2.SetUseOptimized(true) and using 64 bit code

# Environment

Windows 7, .NET 4.6.1, OpenCvSharp 3.4.1.20180319

# What did you do when you faced the problem?

Was able to work around it by ensuring UseOptimized(false) before the call to GaussianBlur
Banding goes away if using Emgu, or if you set "prefer 32bit code" to true

## Example code:

```
var mat2 = new Mat(@"d:\aa.tif");

Mat floatImage2 = new Mat();
mat2.ConvertTo(floatImage2, MatType.CV_32FC1);
floatImage2 = new Mat(floatImage2, new Rect(0, 0, image.Image.PixelWidth, image.Image.PixelHeight));

Cv2.SetUseOptimized(true);
var blurredImage2 = floatImage2.GaussianBlur(new Size(101, 101), 32.0, 32.0);
blurredImage2.SaveImage(@"d:\blurred2Opt.png");
Cv2.SetUseOptimized(false);
var blurredImage = floatImage2.GaussianBlur(new Size(101, 101), 32.0, 32.0);
blurredImage.SaveImage(@"d:\blurred2NoOpt.png");
```

## Output:

```
left image

```

## What did you intend to be?

right image
![cvresults](https://user-images.githubusercontent.com/16797448/47054552-556f6300-d167-11e8-94bf-c3fdfa50f7bf.JPG)

**Comment by shimat** [comment] 2018-10-17 05:54
I translated your program into original OpenCV (C++) and tried it. I could reproduce your problem.
When I upgraded the version of OpenCV from 3.4.1 to 3.4.3, the problem seems to be solved.

```c++
int main()
{
    cv::Mat mat = cv::imread(R"(C:\lenna.png)", cv::IMREAD_GRAYSCALE);
    cv::Mat floatImage;
    mat.convertTo(floatImage, CV_32FC1);

    cv::setUseOptimized(true);
    cv::Mat blurredImage1;
    cv::GaussianBlur(floatImage, blurredImage1, cv::Size(101, 101), 32.0, 32.0);
    cv::imwrite(R"(C:\temp\blur1.png)", blurredImage1);

    cv::setUseOptimized(false);
    cv::Mat blurredImage2;
    cv::GaussianBlur(floatImage, blurredImage2, cv::Size(101, 101), 32.0, 32.0);
    cv::imwrite(R"(C:\temp\blur2.png)", blurredImage2);

    return 0;
}
```

![diff](https://user-images.githubusercontent.com/4434824/47064926-3088f780-d21c-11e8-8755-31f7f38cfb15.png)

It seems that OpenCV4 will be released shortly, so I am planning to not update to 3.4.3.

**Closed** 2018-11-18 04:56 UTC
Labels: problem
